
spring:
  profiles:
    group:
      dev: 
        - dev-app
        - comm
      prod:
        - prod-app
        - comm

---

spring:
  config:
    activate:
      on-profile: comm
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: folder
    password: 1234

---

spring:
  config:
    activate:
      on-profile: dev-app
  datasource:
    url: jdbc:mariadb://localhost:23306/edu

---

spring:
  config:
    activate:
      on-profile: prod-app
  datasource:
    url: jdbc:mariadb://DB:3306/edu
